swagger: '2.0'
info:
  title: Health Check API
  version: '1.0'
host: 'europe-west3-ceremonial-tea-407209.cloudfunctions.net'
schemes:
  - https
paths:
  /health:
    get:
      summary: Get health status of the service
      parameters:
        - name: message
          in: query
          description: Optional message to include in the health status response
          required: false
          type: string
      responses:
        '200':
          description: Health status of the service
          schema:
            type: object
            properties:
              healthy:
                type: boolean
              message:
                type: string
        '400':
          description: Invalid parameter provided
          schema:
            type: object
            properties:
              code:
                type: integer
              message:
                type: string