# This is a basic workflow to help you get started with Actions
name: Continious Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - name: health
            test_dir: "health"
            entry_point: "get_health"
            source_dir: "src/health"
            description: "Health status endpoint."
          - name: transform
            test_dir: "transform"
            entry_point: "post_transform"
            source_dir: "src/transform"
            description: "Transformation endpoint."

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v4"

      # Authenticating at GCP
      # see https://github.com/google-github-actions/deploy-cloud-functions
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Setting up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # see https://github.com/google-github-actions/deploy-cloud-functions
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: ${{ matrix.function.name }}
          entry_point: ${{ matrix.function.entry_point }}
          source_dir: ${{ matrix.function.source_dir }}
          runtime: "python312"
          region: "europe-west3"
          description: ${{ matrix.function.description }}