name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:

  build_and_push_docker:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ steps.auth.outputs.project_id }}/my-application:latest .

      - name: Push Docker image to GCR
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT }} | docker login -u _json_key --password-stdin https://gcr.io
          docker push gcr.io/${{ steps.auth.outputs.project_id }}/my-application:latest

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - name: health
            test_dir: "health"
            entry_point: "get_health"
            source_dir: "src/health"
            description: "Health status endpoint."
          - name: transform
            test_dir: "transform"
            entry_point: "post_transform"
            source_dir: "src/transform"
            description: "Transformation endpoint."

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: ${{ matrix.function.name }}
          entry_point: ${{ matrix.function.entry_point }}
          source_dir: ${{ matrix.function.source_dir }}
          runtime: "python312"
          region: "europe-west3"
          description: ${{ matrix.function.description }}
